### ISSUE TITLE
No output from container. Get several error messages

### ISSUE THREAD

**Issue by kad-meedel** [bitnami/bitnami-docker-jenkins-exporter#1]
I use the docker image from bitnami/jenkins-exporter:latest
with the needed variables.
I run the container within a wsl2 environment with ubuntu 20.04 in Windows

I get no response from the container when I use http://localhost:9118

I see this in de container logging:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/bitnami/python/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/opt/bitnami/python/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/bitnami/python/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/opt/bitnami/python/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/opt/bitnami/python/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/prometheus_client/exposition.py", line 54, in do_GET
    self.wfile.write(generate_latest(core.REGISTRY))
----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 54352)
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/prometheus_client/exposition.py", line 33, in generate_latest
    for metric in registry.collect():
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/prometheus_client/core.py", line 54, in collect
    for metric in collector.collect():
  File "./jenkins_exporter.py", line 34, in collect
    jobs = self._request_data()
  File "./jenkins_exporter.py", line 86, in _request_data
    return parsejobs(url)
  File "./jenkins_exporter.py", line 67, in parsejobs
    response = requests.get(myurl, params=params, verify=(not self._insecure))
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/opt/bitnami/jenkins-exporter/venv/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory

**Comment by yilmi** [comment]
Hi @kad-meedel, ​I did start this container without any issue. ​Could you share some reproduction steps with us?

Thanks,
Yass

**Comment by kad-meedel** [comment]
I run the container within a wsl2 environment ( Ubuntu 20.04.1 LTS (Focal Fossa) )
docker run -p 9118:9118 --name jenkins-exporter  bitnami/jenkins-exporter:latest -j https://dev-svc.in.kadaster.nl/jenkins-test -p 9118
In a browser ( chrome or Edge ) I use the address localhost:9118 
I get a blank screen.

When I refresh this screen I get the errors mentioned above from the container log.

And no data in the browser.

regards
Bert

**Comment by yilmi** [comment]
Thanks @kad-meedel, I wanted to make sure you were reaching a Jenkins instance using HTTPS/TLS. This seems to come from the python requests module that Jenkins Exporter uses which would fail when a Certificate is not signed by a known CA.

The Jenkins exporter project has an option `-k` in its documentation that allow insecure connections (which means, the remote end's certificate will not be authenticated using the available root certificate authority certificates.). You can find where this parameter is used [here](https://github.com/lovoo/jenkins_exporter/blob/master/jenkins_exporter.py#L65).

If you have a self or a custom CA signed certificate, jenkins exporter won't be able to authenticate it, hence the error you got there.

Careful in using this option as your exporter would trust any certificate returned by the remote end, which opens the way to [Man-In-The-Middle attacks ](https://en.wikipedia.org/wiki/Man-in-the-middle_attack).

An option would be to create a Dockerfile based on this image, to which you would copy your Self-Signed or Custom CA certificates as described in the FILES list of the [update-ca-certificates manual](https://manpages.debian.org/buster/ca-certificates/update-ca-certificates.8.en.html) then run the command. If you need any additional packages, you can use the [install_packages](https://github.com/bitnami/minideb#why-use-minideb) command.
